-- Your SQL goes here
CREATE TABLE persona (
    CODIGO SERIAL  PRIMARY KEY,
    IDENTIFICACION VARCHAR(20) ,
    NOMBRE TEXT,
    GENERO VARCHAR(20),
    ESTADOCIVIL VARCHAR(30),
    FECHANACIMIENTO VARCHAR(30),
    TELEFONO VARCHAR(20) ,
    DIRECCION TEXT,
    EMAIL VARCHAR(30) ,
    VALIDADO BOOLEAN ,
    OBSERVACION TEXT
)