-- Your SQL goes here
CREATE TABLE persona (
    CODIGO SERIAL  PRIMARY KEY,
    IDENTIFICACION VARCHAR(20) ,
    NOMBRE TEXT,
    GENERO VARCHAR(1),
    ESTADOCIVIL VARCHAR(100),
    FECHANACIMIENTO TEXT,
    TELEFONO VARCHAR(10) ,
    DIRECCION TEXT,
    EMAIL VARCHAR(30) ,
    VALIDADO BOOLEAN,
    OBSERVACION TEXT
)